// <auto-generated />
namespace ofCourse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCourseStatusTypetoModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCourseStatusTypetoModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202011222229262_AddCourseStatusTypetoModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
